// gleas_backend/users/students/pvp/constants/gameStates.js

const GAME_STATE = {
    WAITING: "WAITING",
    RPS: "RPS",
    SUBJECT_SELECTION: "SUBJECT_SELECTION",
    DECK_CREATION: "DECK_CREATION",
    DICE_ROLL: "DICE_ROLL",
    AWAITING_CARD_SUMMON: "AWAITING_CARD_SUMMON",
    AWAITING_OPPONENT_ANSWER: "AWAITING_OPPONENT_ANSWER",
    TURN_RESOLUTION: "TURN_RESOLUTION",
    PLAYER_SELECT_CARD: "PLAYER_SELECT_CARD",
    GAME_OVER: "GAME_OVER",
    COMPLETED: "COMPLETED",
    ERROR: "ERROR",
};
  
module.exports = GAME_STATE; 